version: '3.8'

services:
  backend:
    image: dockerspring/restapiimage
    container_name: spring-boot-app
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_NAME: RestApi_project
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Courses
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: saiveena
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    depends_on:
      db:
       condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: Courses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saiveena
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Courses"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: dockerspring/reactjsimage
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
   depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules