version: '3.8'

services:
  backend:
    container_name: backend
    image: openjdk:17-jdk
    build:
      context: ./RestApi_project
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Courses
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=saiveena 
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    container_name: frontend
    build:
      context: ./ReactJs_Project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend

  db:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saiveena
      POSTGRES_DB: Courses
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
